# site settings
title: Manica
subtitle: Marketing Technology
email: contact@manica.io
description: Manica vous accompagne dans la définition et la mise en oeuvre<br />de votre stratégie marketing digitale.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://www.manica.io"
author: Daniele Lodola
street_address: 1B rue Joffre
city: Avignon
state: 
zip_code: 84000
country: France
phone: +33 649 413 298

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 4

# social settings
500px_url:
facebook_url: https://www.facebook.com/manica.marketing
github_url:
gitlab_url: 
instagram_url: 
linkedin_url: https://www.linkedin.com/company/manica-marketing/
pinterest_url:
slack_url:
twitter_url: 

# build settings
markdown: kramdown

sass:
  style: compressed
